### ISSUE TITLE
namespace appended name doesn't match with `host` in ingress

### ISSUE THREAD

**Issue by renanqts** [blake/external-mdns#1]
I falling into the following issue.
If I use `host: my.local` in the ingress, it will advertise it appended with namespace name, something like `my.namespace.local`. It causes an issue due the name advertises doesn't match with the `host` declared in the ingress, in this case, the ALB will refuse the request due to the `wrong` name typed.
I also tried to use the full name (name.namespace.local) into the host, but it will be appended + namespace anyway.
Can you help to solve this issue?

**Comment by blake** [comment]
Hi @renanqts, apologies for the delay in responding to this issue. I see how the current behavior is undesirable. I appreciate you submitting a PR with a proposed fix. I'd be happy to work with you to get this merged. I have a few comments which I'll leave over on the PR.
